name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: D Compiler Installation
      uses: mihails-strasuns/setup-dlang@v0.3.1
      with:
        compiler: ${{ matrix.dc }}
      
    - name: Test
      run: dub test --config=std
